config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :username, :email, :password_digest
  validates_uniqueness_of :username, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user 
      flash[:success] = "Welcome to this super cool app! It's super cool."
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserLoginPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class= "container">
<h2> Create New Account </h2>
<%= form_for :user, url: {action: "create"} do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.button %>

<% end %>
</div>
<br>
<div class= "container">
  <p> Already have an account? <%= link_to "Login here!", new_session_path%></p>
</div>

app/views/users/show.html.erb
<div class= "container"><h2> Yay, you logged in! </h2>
</div>
<br>
<div class= "container">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/wZZ7oFKsKzY?autoplay=1" frameborder="0" allowfullscreen></iframe>
</div>
<br>
<div class= "container">
  <p> Ready to logout? <%= link_to "Get me out of here!", session_path, method: :delete, data: {confirm: "Are you sure to want to logout?"}%></p>
</div>

app/views/welcome/index.html.erb
<div class= "title">
<h1> Welcome To A Site You Would Definitely Want To Login For! </h1>
</div>
<br>
<div class="container">
<p><%= link_to "Login to your account here!", new_session_path%></p>
<br>
<p><%= link_to "Create a new account here!", new_user_path %></p>
</div>